Fix stacked borrow violations
cessen/ropey pull request #61
Opened 2022-05-24 20:16 UTC by Nilstrieb

There was a Stacked Borrows issue in `NodeChildrenInternal::insert` and `NodeChildrenInternal::remove`, where the pointer to `src` was invalidated by creating the pointer to `dst` afterwards.

This also generally improves the unsafe code even further by commenting more on the invariants and how they are upheld. I accidentally introduced a UAF bug after the first fix, so I took a real close look at everything before I found it 😅.

Also runs miri in CI to make sure this crate stays sound in the future, but certain tests are ignored in miri because they take too long. Using smaller testdata for miri is something for the future, I tried to do it but it didn't quite work because the tests indexed into it everywhere, so I gave up.

2022-05-24 20:23 UTC, saethlin commented on src/tree/node_children.rs
> +                ptr::copy(self.nodes.as_ptr().add(idx), dst, len - idx);
I prefer this refactoring:
```rust
let ptr = self.nodes.as_mut_ptr();
ptr::copy(ptr.add(idx), ptr.add(idx + 1), len - idx);
```

2022-05-24 20:38 UTC, Nilstrieb commented
Note: Miri doesn't work on x86 because str-indices uses SIMD there. I cross-ran it on aarch64 locally, we should also do something like this in CI and document it.

2022-05-24 21:44 UTC, cessen commented
Thanks so much for this!  I tried to run Ropey through miri before, but wasn't able to get it to run in anything less than what seemed like an infinite amount of time, so I gave up.  (IMO the miri docs could use some improvement, there.)

I'll give this a thorough review the next chance I get.

> Note: Miri doesn't work on x86 because str-indices uses SIMD there. I cross-ran it on aarch64 locally, we should also do something like this in CI and document it.

I think it would make more sense to add a feature flag to [str_indices](https://github.com/cessen/str_indices) (and a corresponding flag in Ropey) to disable/enable SIMD, and disable it for the miri run.  I don't think that would be too hard, since all the SIMD stuff is very compartmentalized.  And we'll need that anyway to keep miri working when we [implement SIMD for aarch64](https://github.com/cessen/str_indices/issues/10).

In any case, we'll either need to deal with that before merging this, or remove the CI stuff from this PR.  CI is currently failing for that reason, it appears.

2022-05-25 01:11 UTC, saethlin commented
> IMO the miri docs could use some improvement, there.

Where did you look in the Miri docs? The README? If I wrote a section about this, what keywords would you be looking for?

2022-05-26 01:38 UTC, cessen commented
I've added a "simd" cargo feature flag to str_indices, and a corresponding "simd" feature flag to Ropey that controls it when building Ropey.  So you should be able to just disable default features in Ropey to get miri to run now.

@saethlin 
> Do you mean you looked at the rust-lang/miri README?

Looking over the readme again, it actually looks fine to me now.  The thing I missed last time was how to disable tests (e.g. long-running ones) just for miri, but it looks like it's covered.  I don't know if it was updated since I last checked it out, or if I just totally missed it (very possible).

2022-05-26 10:11 UTC, Nilstrieb commented
A few rebases later I added the flag to CI and also did the small change in insert/remove that Saethlin proposed above. Everything should be good to go now.

2022-05-26 19:55 UTC, cessen commented
Awesome!  It'll probably still be a bit before I have a chance to give this a proper review, but I definitely want to get this merged--it's a great contribution to Ropey's memory safety and *very much* appreciated.  Thanks so much!

2022-05-26 19:58 UTC, Nilstrieb commented
Thanks for the quick response and positive feedback as well! I also wanted to add that the unsafe code here was really good and well encapsulated, a really good example

2022-05-28 22:24 UTC, cessen requested changes
There are a whole lot of superfluous/cosmetic changes to the code here, mostly involving making a temporary `len` variable.  It's to the point that I can't easily find where the actual safety-relevant change is because the code diff is so noisy.

I don't mean to knock your efforts here, but please undo all code changes that aren't the safety-related one(s).  However, I do like your additional safety comments, so please leave those.  And of course, keep all the stuff for running miri.

2022-05-28 22:24 UTC, cessen commented on src/tree/node_children.rs
> +            unsafe { mem::transmute(&self.nodes[..len]) }
I like the added safety note, but moving the length out into a separate variable seems superfluous to me.  Unless there was something wrong with the code that I'm not seeing, I'd rather leave the code itself as-is.  Same goes for the other places where you split it out.

2022-05-29 09:09 UTC, Nilstrieb commented
I reverted all the style changes so that the only remaining changes are the actual fixes (the pointer in `ptr::copy_nonoverlapping`) and additional comments

2022-05-29 21:24 UTC, cessen approved these changes

2022-05-29 21:27 UTC, cessen commented
Awesome, thanks so much for this!  And wow... that's a really subtle change.  I even more appreciate you undoing the other changes now, because at first glance the fix itself also looks superfluous... but in fact isn't.

Thanks again!

2022-05-29 21:28 UTC, merged